[project]
name = "assessment"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.3"
dependencies = [
    "numpy>=2.3.2",
    "pandas>=2.3.1",
    "requests>=2.32.4",
    "streamlit>=1.48.0",
]
